/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AbrirEmpresaEmSaoBernardoDoCampoRouteImport } from './routes/abrir-empresa-em-sao-bernardo-do-campo'
import { Route as ContabilidadeEmSaoBernardoDoCampoRouteImport } from './routes/contabilidade-em-sao-bernardo-do-campo'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ServicosIndexRouteImport } from './routes/servicos.index'
import { Route as ServicosSlugRouteImport } from './routes/servicos.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AbrirEmpresaEmSaoBernardoDoCampoRoute =
  AbrirEmpresaEmSaoBernardoDoCampoRouteImport.update({
    id: '/abrir-empresa-em-sao-bernardo-do-campo',
    path: '/abrir-empresa-em-sao-bernardo-do-campo',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContabilidadeEmSaoBernardoDoCampoRoute =
  ContabilidadeEmSaoBernardoDoCampoRouteImport.update({
    id: '/contabilidade-em-sao-bernardo-do-campo',
    path: '/contabilidade-em-sao-bernardo-do-campo',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosIndexRoute = ServicosIndexRouteImport.update({
  id: '/servicos/',
  path: '/servicos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosSlugRoute = ServicosSlugRouteImport.update({
  id: '/servicos/$slug',
  path: '/servicos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abrir-empresa-em-sao-bernardo-do-campo': typeof AbrirEmpresaEmSaoBernardoDoCampoRoute
  '/contabilidade-em-sao-bernardo-do-campo': typeof ContabilidadeEmSaoBernardoDoCampoRoute
  '/contato': typeof ContatoRoute
  '/sobre': typeof SobreRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/servicos/': typeof ServicosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abrir-empresa-em-sao-bernardo-do-campo': typeof AbrirEmpresaEmSaoBernardoDoCampoRoute
  '/contabilidade-em-sao-bernardo-do-campo': typeof ContabilidadeEmSaoBernardoDoCampoRoute
  '/contato': typeof ContatoRoute
  '/sobre': typeof SobreRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/blog': typeof BlogIndexRoute
  '/servicos': typeof ServicosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abrir-empresa-em-sao-bernardo-do-campo': typeof AbrirEmpresaEmSaoBernardoDoCampoRoute
  '/contabilidade-em-sao-bernardo-do-campo': typeof ContabilidadeEmSaoBernardoDoCampoRoute
  '/contato': typeof ContatoRoute
  '/sobre': typeof SobreRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/servicos/$slug': typeof ServicosSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/servicos/': typeof ServicosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abrir-empresa-em-sao-bernardo-do-campo'
    | '/contabilidade-em-sao-bernardo-do-campo'
    | '/contato'
    | '/sobre'
    | '/blog/$slug'
    | '/servicos/$slug'
    | '/blog/'
    | '/servicos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abrir-empresa-em-sao-bernardo-do-campo'
    | '/contabilidade-em-sao-bernardo-do-campo'
    | '/contato'
    | '/sobre'
    | '/blog/$slug'
    | '/servicos/$slug'
    | '/blog'
    | '/servicos'
  id:
    | '__root__'
    | '/'
    | '/abrir-empresa-em-sao-bernardo-do-campo'
    | '/contabilidade-em-sao-bernardo-do-campo'
    | '/contato'
    | '/sobre'
    | '/blog/$slug'
    | '/servicos/$slug'
    | '/blog/'
    | '/servicos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbrirEmpresaEmSaoBernardoDoCampoRoute: typeof AbrirEmpresaEmSaoBernardoDoCampoRoute
  ContabilidadeEmSaoBernardoDoCampoRoute: typeof ContabilidadeEmSaoBernardoDoCampoRoute
  ContatoRoute: typeof ContatoRoute
  SobreRoute: typeof SobreRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ServicosSlugRoute: typeof ServicosSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ServicosIndexRoute: typeof ServicosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abrir-empresa-em-sao-bernardo-do-campo': {
      id: '/abrir-empresa-em-sao-bernardo-do-campo'
      path: '/abrir-empresa-em-sao-bernardo-do-campo'
      fullPath: '/abrir-empresa-em-sao-bernardo-do-campo'
      preLoaderRoute: typeof AbrirEmpresaEmSaoBernardoDoCampoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contabilidade-em-sao-bernardo-do-campo': {
      id: '/contabilidade-em-sao-bernardo-do-campo'
      path: '/contabilidade-em-sao-bernardo-do-campo'
      fullPath: '/contabilidade-em-sao-bernardo-do-campo'
      preLoaderRoute: typeof ContabilidadeEmSaoBernardoDoCampoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/': {
      id: '/servicos/'
      path: '/servicos'
      fullPath: '/servicos/'
      preLoaderRoute: typeof ServicosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/$slug': {
      id: '/servicos/$slug'
      path: '/servicos/$slug'
      fullPath: '/servicos/$slug'
      preLoaderRoute: typeof ServicosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbrirEmpresaEmSaoBernardoDoCampoRoute: AbrirEmpresaEmSaoBernardoDoCampoRoute,
  ContabilidadeEmSaoBernardoDoCampoRoute:
    ContabilidadeEmSaoBernardoDoCampoRoute,
  ContatoRoute: ContatoRoute,
  SobreRoute: SobreRoute,
  BlogSlugRoute: BlogSlugRoute,
  ServicosSlugRoute: ServicosSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ServicosIndexRoute: ServicosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
